// App
export const HANDLE_ERROR = 'HANDLE_ERROR';
export const SAVE_IP = 'SAVE_IP';
export const UPDATE_SELECTED_MATCH = 'UPDATE_SELECTED_MATCH';
export const UPDATE_SELECTED_CONTEST = 'UPDATE_SELECTED_CONTEST';
export const UPDATE_JOINCONTEST_REQUEST = 'UPDATE_JOINCONTEST_REQUEST';
export const UPDATE_FULL_MATCH = 'UPDATE_FULL_MATCH';
export const UPDATE_DARK_MODE = 'UPDATE_DARK_MODE';
export const UPDATE_JOIN_MODAL = 'UPDATE_JOIN_MODAL';
export const UPDATE_CREATED_TEAM = 'UPDATE_CREATED_TEAM';

// User
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

// team
export const SAVE_ALL_PLAYERS = 'SAVE_ALL_PLAYERS';
export const UPDATE_PLAYERS = 'UPDATE_PLAYERS';
export const UPDATE_ERROR_MESSAGE = 'UPDATE_ERROR_MESSAGE';
export const UPDATE_BLOCKLIST = 'UPDATE_BLOCKLIST';
export const UPDATE_CREDITS = 'UPDATE_CREDITS';
export const UPDATE_TEAM = 'UPDATE_TEAM';
export const UPDATE_TEAM_COUNT = 'UPDATE_TEAM_COUNT';
export const UPDATE_CAPTAIN = 'UPDATE_CAPTAIN';
export const UPDATE_VC_CAPTAIN = 'UPDATE_VC_CAPTAIN';
export const CLEAR_TEAM = 'CLEAR_TEAM';
export const UPDATE_LOCK = 'UPDATE_LOCK';

// match
export const UPDTAE_MATCH_META = 'UPDTAE_MATCH_META';
export const UPDATE_MY_CONTESTS = 'UPDATE_MATCH_PLAYERS';
export const UPDATE_USER_TEAMS = 'UPDATE_USER_TEAMS';
export const UPDATE_PLAYERS_POINTS = 'UPDATE_PLAYERS_POINTS';
export const UPDATE_LOADING = 'UPDATE_LOADING';


