// App
export const HANDLE_ERROR = 'HANDLE_ERROR';
export const SAVE_IP = 'SAVE_IP';
export const UPDATE_SELECTED_MATCH = 'UPDATE_SELECTED_MATCH';
export const UPDATE_SELECTED_CONTEST = 'UPDATE_SELECTED_CONTEST';
export const UPDATE_JOINCONTEST_REQUEST = 'UPDATE_JOINCONTEST_REQUEST';
export const UPDATE_FULL_MATCH = 'UPDATE_FULL_MATCH';
export const UPDATE_DARK_MODE = 'UPDATE_DARK_MODE';

// User
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

// team
export const SAVE_ALL_PLAYERS = 'SAVE_ALL_PLAYERS';
export const UPDATE_PLAYERS = 'UPDATE_PLAYERS';
export const UPDATE_ERROR_MESSAGE = 'UPDATE_ERROR_MESSAGE';
export const UPDATE_BLOCKLIST = 'UPDATE_BLOCKLIST';
export const UPDATE_CREDITS = 'UPDATE_CREDITS';
export const UPDATE_TEAM = 'UPDATE_TEAM';
export const UPDATE_TEAM_COUNT = 'UPDATE_TEAM_COUNT';
export const UPDATE_CAPTAIN = 'UPDATE_CAPTAIN';
export const UPDATE_VC_CAPTAIN = 'UPDATE_VC_CAPTAIN';
export const CLEAR_TEAM = 'CLEAR_TEAM';
