// App
export const HANDLE_ERROR = 'HANDLE_ERROR';
export const SAVE_IP = 'SAVE_IP';
export const UPDATE_SELECTED_MATCH = 'UPDATE_SELECTED_MATCH';
export const UPDATE_SELECTED_CONTEST = 'UPDATE_SELECTED_CONTEST';

// User
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

// team
export const UPDATE_PLAYERS = 'UPDATE_PLAYERS';
export const UPDATE_BLOCKLIST = 'UPDATE_BLOCKLIST';
export const UPDATE_CREDITS = 'UPDATE_CREDITS';
export const UPDATE_TEAM_COUNT = 'UPDATE_TEAM_COUNT';
export const UPDATE_CAPTAIN = 'UPDATE_CAPTAIN';
export const UPDATE_VC_CAPTAIN = 'UPDATE_VC_CAPTAIN';
export const CLEAR_TEAM = 'CLEAR_TEAM';
