export default {
  fantasy_points: require('../assets/icons/fantasy_points.png'),
  minus: require('../assets/icons/minus.png'),
  comparePlayer: require('../assets/icons/comparePlayer.png'),
  vs: require('../assets/icons/vs.png'),
  levels: require('../assets/icons/levels.png'),
  drawer_wallet: require('../assets/icons/drawer_wallet.png'),
  cash_icon: require('../assets/icons/cash_icon.png'),
  joystick: require('../assets/icons/joystick.png'),
  question_icon: require('../assets/icons/question_icon.png'),
  chat_icon: require('../assets/icons/chat_icon.png'),
  winning_cup: require('../assets/icons/winning_cup.png'),
  plus: require('../assets/icons/plus.png'),
  cricket_off: require('../assets/icons/cricket_off.png'),
  cricket_on: require('../assets/icons/cricket_on.png'),
  football_on: require('../assets/icons/football_on.png'),
  football_off: require('../assets/icons/football_off.png'),
  chart: require('../assets/icons/chart.png'),
  notify_more: require('../assets/icons/notify_more.png'),
  cash_paper: require('../assets/icons/cash_paper.png'),
  link: require('../assets/icons/link.png'),
  twitter: require('../assets/icons/twitter.png'),
  more_share: require('../assets/icons/more_share.png'),
  friends: require('../assets/icons/friends.png'),
  help: require('../assets/icons/help.png'),


  profile_round: require('../assets/images/profile_round.png'),
  cricket_icon: require('../assets/images/cricket_icon.png'),
  football_icon: require('../assets/images/football_icon.png'),
  australia_flag: require('../assets/images/in_flag.png'),
  logo_new: require('../assets/images/logo_new.png'),
  ground: require('../assets/images/ground.png'),
  footbal_on: require('../assets/images/footbal_on.png'),
  user_temp_profile: require('../assets/images/user_temp_profile.png'),
  promoNotification: require('../assets/images/promoNotification.png'),
  verify_account: require('../assets/images/verify_account.png'),
  ground_two: require('../assets/images/ground_two.png'),
  trophy: require('../assets/images/trophy.png'),
  level_box: require('../assets/images/level_box.png'),
  myTeamsBackground: require('../assets/images/myTeamsBackground.png'),
  goal_money: require('../assets/images/goal_money.png'),
  prize1: require('../assets/images/prize1.png'),
  prize2: require('../assets/images/prize2.png'),
  prize3: require('../assets/images/prize3.png'),
  createContestBanner: require('../assets/images/createContestBanner.png'),
  shareToFriends: require('../assets/images/shareToFriends.png'),
  stadium: require('../assets/images/stadium.png'),
  stadium_2: require('../assets/images/stadium_2.png'),
  
  // images that can't convert into svg's
  gpay: require('../assets/images/gpay.png'),
  paytm: require('../assets/images/paytm.png'),
  phonepe: require('../assets/images/phonepe.png'),
  upi: require('../assets/images/upi.png'),
  // crickert and bolwer image
  coin: require('../assets/images/coin.png'),

  // flags
  AUS: require('../assets/images/flags/AUS.png'),
  ENG: require('../assets/images/flags/ENG.png'),

  banner1: require('../assets/temp/banner1.png'),
  banner2: require('../assets/temp/banner2.png'),
  playerImage: require('../assets/temp/playerimage.png'),
  indianflag: require('../assets/temp/indianflag.png'),
  aus_flag: require('../assets/temp/aus_flag.jpeg'),
  teamIndia: require('../assets/temp/teamIndia.png'),
  player: require('../assets/temp/player.png'),
  s_flag1: require('../assets/temp/s_flag1.png'),
  s_flag2: require('../assets/temp/s_flag2.png'),
  person: require('../assets/temp/person.png'),
};
