export default {
  react_logo: require('../assets/icons/react_logo.jpeg'),

  home_tab: require('../assets/icons/home_tab.png'),
  contest_tab: require('../assets/icons/contest_tab.png'),
  leader_tab: require('../assets/icons/leader_tab.png'),
  more_tab: require('../assets/icons/more_tab.png'),
  contest_tab_on: require('../assets/icons/contest_tab_on.png'),
  leader_tab_on: require('../assets/icons/leader_tab_on.png'),
  home_tab_off: require('../assets/icons/home_tab_off.png'),
  more_tab_on: require('../assets/icons/more_tab_on.png'),
  fantasy_points: require('../assets/icons/fantasy_points.png'),
  Info_Square: require('../assets/icons/Info_Square.png'),
  indicator: require('../assets/icons/indicator.png'),
  minus: require('../assets/icons/minus.png'),
  filter: require('../assets/icons/filter.png'),
  walletIcon: require('../assets/icons/walletIcon.png'),
  money: require('../assets/icons/money.png'),
  cup: require('../assets/icons/cup.png'),
  M: require('../assets/icons/M.png'),
  comparePlayer: require('../assets/icons/comparePlayer.png'),
  vs: require('../assets/icons/vs.png'),
  download: require('../assets/icons/download.png'),

  running_clock: require('../assets/icons/running_clock.png'),
  bell: require('../assets/icons/bell.png'),

  profile_round: require('../assets/images/profile_round.png'),
  cricket_icon: require('../assets/images/cricket_icon.png'),
  football_icon: require('../assets/images/football_icon.png'),
  australia_flag: require('../assets/images/in_flag.png'),
  south_africa_flag: require('../assets/images/flag_pak.png'),
  topBarbell: require('../assets/images/topBarbell.png'),
  logo: require('../assets/images/logo.png'),
  logo_new: require('../assets/images/logo_new.png'),
  wallet: require('../assets/images/wallet.png'),
  logo_back_rectangle: require('../assets/images/logo_back_rectangle.png'),
  ground: require('../assets/images/ground.png'),
  cricket_off: require('../assets/images/cricket_off.png'),
  footbal_on: require('../assets/images/footbal_on.png'),
  flash: require('../assets/images/flash.png'),
  logoWrapper: require('../assets/images/logoWrapper.png'),

  banner1: require('../assets/temp/banner1.png'),
  playerImage: require('../assets/temp/playerimage.png'),
  indianflag: require('../assets/temp/indianflag.png'),
  aus_flag: require('../assets/temp/aus_flag.jpeg'),
  teamIndia: require('../assets/temp/teamIndia.png'),
  player: require('../assets/temp/player.png'),
};
