export const liveMatchStatsBluprint = Object.seal({
  key: '',
  name: '',
  short_name: '',
  team_a: {
    key: '',
    has_points: false,
    is_batting: false,
    name: '',
    runs: 0,
    wickets: 0,
    overs: 0.0,
  },
  team_b: {
    key: '',
    has_points: false,
    is_batting: false,
    name: '',
    runs: 0,
    wickets: 0,
    overs: 0.0,
  },
  status: null,
  projection: '',
  batters: [
    {
      key: '',
      active: false,
      name: '',
      runs: 0,
      used_balls: 0,
    },
    {
      key: '',
      active: false,
      name: '',
      runs: 0,
      used_balls: 0,
    },
  ],
  bowler: {
    key: '',
    name: '',
    taken_wicket: 0,
    given_runs: 0,
    used_overs: 0.0,
  },
  overInfo: [],
});
